#!/usr/bin/env python3
"""Build the Sonic Fulfillment WordPress theme from the static site in site/.

Turns each page in site/ into a WordPress template, rewrites asset and page
links, and writes:

    wordpress/sonic-fulfillment/      the theme folder
    wordpress/sonic-fulfillment.zip   upload this in Appearance > Themes > Add New

Run again after editing site/ to regenerate the theme. No dependencies.
"""
import re
import shutil
import subprocess
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
OUT = ROOT / "wordpress"
THEME = OUT / "sonic-fulfillment"
VERSION = "1.6.0"

# Static file -> (WordPress page slug, page title). The homepage has no slug.
PAGES = {
    "index.html": (None, "Home"),
    "services.html": ("services", "Services"),
    "how-it-works.html": ("how-it-works", "How it works"),
    "pricing.html": ("pricing", "Pricing"),
    "our-story.html": ("our-story", "Our Story"),
    "contact.html": ("contact", "Contact"),
    "dashboard.html": ("client-login", "Client Login"),
}

FONTS_URL = (
    "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600"
    "&family=Space+Grotesk:wght@400;500;600;700&display=swap"
)


def between(text, start, end, last=False):
    """Return the text between two markers (exclusive)."""
    i = text.rindex(start) if last else text.index(start)
    i += len(start)
    return text[i:text.index(end, i)]


def must_replace(text, old, new):
    if old not in text:
        raise SystemExit(f"Expected to find this in the source, but didn't:\n{old}")
    return text.replace(old, new)


def php_str(text):
    return text.replace("\\", "\\\\").replace("'", "\\'")


def wp_links(html):
    """Point asset and page links at WordPress."""
    html = re.sub(
        r'src="(assets/[^"]+)"',
        lambda m: "src=\"<?php echo esc_url( get_theme_file_uri( '%s' ) ); ?>\"" % m.group(1),
        html,
    )

    def page_link(m):
        slug = PAGES[m.group(1)][0]
        frag = m.group(2) or ""
        if slug is None:
            return "href=\"<?php echo esc_url( home_url( '/%s' ) ); ?>\"" % frag
        if frag:
            return "href=\"<?php echo esc_url( sonic_page_url( '%s' ) . '%s' ); ?>\"" % (slug, frag)
        return "href=\"<?php echo esc_url( sonic_page_url( '%s' ) ); ?>\"" % slug

    names = "|".join(re.escape(n) for n in PAGES)
    return re.sub(r'href="(%s)(#[\w-]+)?"' % names, page_link, html)


# ---------------------------------------------------------------- templates

STYLE_HEADER = """/*
Theme Name: Sonic Fulfillment
Theme URI: https://sonicfulfillment.com
Author: Sonic Fulfillment
Description: Marketing site and client dashboard preview for Sonic Fulfillment, a 3PL in Southern California.
Version: %s
Requires at least: 6.0
Requires PHP: 7.4
License: Proprietary
Text Domain: sonic-fulfillment
*/
""" % VERSION

# Styles the static site doesn't need: other WordPress pages, and the quote form's error line.
EXTRA_CSS = """
/* ---------- WordPress additions ---------- */
.site-bar { background: var(--navy); margin: 16px; border-radius: var(--radius); }
.site-bar .nav-actions { display: flex; }
.entry { padding: clamp(48px, 7vw, 88px) 0; }
.entry > * { max-width: 760px; }
.entry h1 { font-size: clamp(2rem, 4.2vw, 3.25rem); margin-bottom: 24px; }
.entry h2 { font-size: 1.6rem; margin: 1.6em 0 0.6em; }
.entry h3 { font-size: 1.25rem; margin: 1.4em 0 0.5em; }
.entry p, .entry ul, .entry ol { margin: 0 0 1.2em; }
.entry ul { list-style: disc; padding-left: 1.3em; }
.entry ol { list-style: decimal; padding-left: 1.3em; }
.entry a { color: var(--navy-2); text-decoration: underline; text-decoration-color: var(--gold); text-underline-offset: 4px; }
.entry article + article { margin-top: 56px; padding-top: 56px; border-top: 1px solid var(--line); }
@media (max-width: 600px) {
  .site-bar { margin: 8px; border-radius: 20px; }
  .site-bar .btn-outline { display: none; }
}
"""

FUNCTIONS_PHP = r"""<?php
/**
 * Sonic Fulfillment theme setup.
 *
 * Generated by tools/build_wordpress_theme.py from the static site in site/.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'SONIC_VERSION', '__VERSION__' );
define( 'SONIC_LOGIN_SLUG', 'client-login' );
define( 'SONIC_QUOTE_EMAIL', 'info@sonicfulfillment.com' );

function sonic_setup() {
	add_theme_support( 'title-tag' );
	add_theme_support( 'html5', array( 'script', 'style', 'search-form', 'gallery', 'caption' ) );
}
add_action( 'after_setup_theme', 'sonic_setup' );

/**
 * Each inner page is a normal WordPress page whose slug matches a
 * page-{slug}.php template in this theme.
 */
function sonic_pages() {
	return array(
__PAGES__
	);
}

/**
 * Create any missing pages when the theme is activated, and again after a
 * theme update that adds new ones.
 */
function sonic_create_pages() {
	foreach ( sonic_pages() as $slug => $title ) {
		if ( get_page_by_path( $slug ) ) {
			continue;
		}
		wp_insert_post(
			array(
				'post_type'   => 'page',
				'post_title'  => $title,
				'post_name'   => $slug,
				'post_status' => 'publish',
			)
		);
	}
	update_option( 'sonic_pages_version', SONIC_VERSION );
}
add_action( 'after_switch_theme', 'sonic_create_pages' );

function sonic_maybe_create_pages() {
	if ( get_option( 'sonic_pages_version' ) !== SONIC_VERSION ) {
		sonic_create_pages();
	}
}
add_action( 'admin_init', 'sonic_maybe_create_pages' );

function sonic_page_url( $slug ) {
	$page = get_page_by_path( $slug );
	return $page ? get_permalink( $page ) : home_url( '/' . $slug . '/' );
}

function sonic_is_login_page() {
	return is_page( SONIC_LOGIN_SLUG );
}

function sonic_assets() {
	wp_enqueue_style( 'sonic-fonts', '__FONTS_URL__', array(), null );

	// The dashboard has its own stylesheet; its class names overlap with the main site's.
	if ( sonic_is_login_page() ) {
		wp_enqueue_style( 'sonic-dashboard', get_theme_file_uri( 'assets/css/dashboard.css' ), array(), SONIC_VERSION );
		wp_enqueue_script( 'sonic-dashboard', get_theme_file_uri( 'assets/js/dashboard.js' ), array(), SONIC_VERSION, true );
		return;
	}

	wp_enqueue_style( 'sonic-style', get_stylesheet_uri(), array(), SONIC_VERSION );
	wp_enqueue_script( 'sonic-main', get_theme_file_uri( 'assets/js/main.js' ), array(), SONIC_VERSION, true );
	wp_localize_script( 'sonic-main', 'sonicQuote', array( 'ajaxUrl' => admin_url( 'admin-ajax.php' ) ) );
}
add_action( 'wp_enqueue_scripts', 'sonic_assets' );

function sonic_head() {
	echo '<link rel="preconnect" href="https://fonts.googleapis.com">' . "\n";
	echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>' . "\n";

	// A site icon set in Settings > General takes over from the bundled one.
	if ( ! has_site_icon() ) {
		echo '<link rel="icon" type="image/png" href="' . esc_url( get_theme_file_uri( 'assets/mark.png' ) ) . '">' . "\n";
	}

	$descriptions = array(
__DESCRIPTIONS__
	);
	$description = '';
	if ( is_front_page() ) {
		$description = '__HOME_DESCRIPTION__';
	} else {
		foreach ( $descriptions as $slug => $text ) {
			if ( is_page( $slug ) ) {
				$description = $text;
				break;
			}
		}
	}
	if ( $description ) {
		echo '<meta name="description" content="' . esc_attr( $description ) . '">' . "\n";
	}
}
add_action( 'wp_head', 'sonic_head', 1 );

/**
 * Quote form: emails the request to SONIC_QUOTE_EMAIL and sends the customer
 * an automatic confirmation. Use the sonic_quote_recipient filter to send
 * requests somewhere else.
 *
 * No nonce: the form is public and page caches would serve expired ones.
 * A honeypot field catches basic bots instead.
 */
function sonic_handle_quote() {
	if ( ! empty( $_POST['company_url'] ) ) {
		wp_send_json_success();
	}

	$name     = isset( $_POST['name'] ) ? sanitize_text_field( wp_unslash( $_POST['name'] ) ) : '';
	$email    = isset( $_POST['email'] ) ? sanitize_email( wp_unslash( $_POST['email'] ) ) : '';
	$website  = isset( $_POST['website'] ) ? sanitize_text_field( wp_unslash( $_POST['website'] ) ) : '';
	$volume   = isset( $_POST['volume'] ) ? sanitize_text_field( wp_unslash( $_POST['volume'] ) ) : '';
	$skus     = isset( $_POST['skus'] ) ? sanitize_text_field( wp_unslash( $_POST['skus'] ) ) : '';

	if ( '' === $name || ! is_email( $email ) ) {
		wp_send_json_error( array( 'message' => 'Enter your name and a valid email.' ), 400 );
	}

	$to      = apply_filters( 'sonic_quote_recipient', SONIC_QUOTE_EMAIL );
	$subject = 'Quote request from ' . $name;
	$details = "Name: $name\nEmail: $email\nStore website: $website\nOrders per month: $volume\nNumber of SKUs: $skus\n";
	$headers = array( 'Reply-To: ' . $name . ' <' . $email . '>' );

	if ( ! wp_mail( $to, $subject, $details, $headers ) ) {
		wp_send_json_error( array( 'message' => 'The request could not be sent.' ), 500 );
	}

	// The request has reached us, so a failed confirmation must not show the customer an error.
	sonic_send_quote_confirmation( $name, $email, $details, $to );
	wp_send_json_success();
}

function sonic_send_quote_confirmation( $name, $email, $details, $reply_to ) {
	$subject = 'Thank you for contacting Sonic Fulfillment';
	$body    = "Hi $name,\n\n"
		. "Thank you so much for contacting Sonic Fulfillment. We appreciate your time and your interest in working with us.\n\n"
		. "We have received your details and are working on your quote. We will get back to you by email as soon as it is ready.\n\n"
		. "Here is what you sent us:\n\n$details\n"
		. "If you would like to add anything, reply to this email or call us at (949) 912-2931.\n\n"
		. "Sonic Fulfillment\n"
		. "3731 W Warner Ave, Santa Ana, CA 92704\n"
		. "(949) 912-2931 | info@sonicfulfillment.com\n";
	$headers = array( 'Reply-To: Sonic Fulfillment <' . $reply_to . '>' );

	return wp_mail( $email, $subject, $body, $headers );
}
add_action( 'wp_ajax_sonic_quote', 'sonic_handle_quote' );
add_action( 'wp_ajax_nopriv_sonic_quote', 'sonic_handle_quote' );
"""

HEADER_PHP = r"""<?php
/**
 * Document head, shared by every page except the client dashboard.
 */
?><!doctype html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>
"""

FOOTER_PHP = r"""<?php
/**
 * Site footer.
 */
?>
__FOOTER__

<?php wp_footer(); ?>
</body>
</html>
"""

PAGE_PHP = r"""<?php
/**
 * __TITLE__ page. Generated from site/__SOURCE__.
 */
get_header();
?>

__BODY__
<?php
get_footer();
"""

INDEX_PHP = r"""<?php
/**
 * Fallback for posts and for any page without its own template.
 */
get_header();
?>

<div class="site-bar">
  <nav class="nav" aria-label="Main">
    <a class="brand" href="<?php echo esc_url( home_url( '/' ) ); ?>" aria-label="Sonic Fulfillment home"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/logo-white.png' ) ); ?>" alt="Sonic Fulfillment" width="777" height="455"></a>
    <div class="nav-actions">
      <a class="btn btn-outline" href="<?php echo esc_url( sonic_page_url( SONIC_LOGIN_SLUG ) ); ?>">Client login</a>
      <a class="btn btn-gold" href="<?php echo esc_url( sonic_page_url( 'contact' ) ); ?>">Get a quote</a>
    </div>
  </nav>
</div>

<main class="wrap entry">
<?php if ( have_posts() ) : ?>
	<?php while ( have_posts() ) : the_post(); ?>
	<article <?php post_class(); ?>>
		<?php if ( is_singular() ) : ?>
			<h1><?php the_title(); ?></h1>
		<?php else : ?>
			<h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
		<?php endif; ?>
		<?php the_content(); ?>
	</article>
	<?php endwhile; ?>
	<?php the_posts_pagination(); ?>
<?php else : ?>
	<h1>Page not found</h1>
	<p>That page doesn't exist. <a href="<?php echo esc_url( home_url( '/' ) ); ?>">Go to the homepage</a>.</p>
<?php endif; ?>
</main>

<?php
get_footer();
"""

DASHBOARD_PHP = r"""<?php
/**
 * Template Name: Client Login
 *
 * Client login and dashboard preview. Used automatically for the page with the
 * slug "client-login". Sign-in is a preview: any email and password opens the
 * dashboard with sample data.
 */
?><!doctype html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>

__BODY__

<?php wp_footer(); ?>
</body>
</html>
"""

README_TXT = """Sonic Fulfillment WordPress theme
=================================

Install
1. In WordPress, go to Appearance > Themes > Add New Theme > Upload Theme.
2. Choose sonic-fulfillment.zip, click Install Now, then Activate.
   (If an older version is installed, choose "Replace current with uploaded".)

The homepage shows at your site's address straight away. Activating the theme
also creates these pages: Services, How it works, Pricing, Our Story, Contact and
Client Login. Keep their addresses (slugs) as they are, because each one is
matched to its design by its slug.

Before launch
- Settings > Permalinks: choose "Post name" and save, so pages get clean
  addresses such as /services/.
- Quote form: each request is emailed to info@sonicfulfillment.com, and the
  customer automatically gets a thank-you email saying their quote is being
  prepared. Most hosts need an SMTP plugin (for example WP Mail SMTP), set up
  with the info@sonicfulfillment.com mailbox, for these emails to arrive
  reliably. Send yourself a test request.
- Client login: still a preview. Any email and password opens the dashboard
  with sample data. Real accounts and live data need a connection to the
  warehouse software.
- Text and images are in the theme files, not the WordPress editor. To change
  them, edit site/ and re-run tools/build_wordpress_theme.py.
"""


# -------------------------------------------------------------------- build

def build():
    if THEME.exists():
        shutil.rmtree(THEME)
    (THEME / "assets" / "css").mkdir(parents=True)
    (THEME / "assets" / "js").mkdir(parents=True)

    # Logos and photos
    shutil.copytree(SITE / "assets" / "img", THEME / "assets" / "img")
    for f in (SITE / "assets").glob("*.png"):
        shutil.copy(f, THEME / "assets" / f.name)

    # --- Stylesheet: style.css sits at the theme root, one level above the static one.
    css = (SITE / "assets" / "css" / "style.css").read_text(encoding="utf-8")
    css = must_replace(css, 'url("../img/', 'url("assets/img/')
    (THEME / "style.css").write_text(STYLE_HEADER + "\n" + css + EXTRA_CSS, encoding="utf-8")

    # --- Script: the quote form posts to WordPress instead of the Firebase function.
    js = (SITE / "assets" / "js" / "main.js").read_text(encoding="utf-8")
    js = must_replace(js, "  document.getElementById('year').textContent = new Date().getFullYear();\n\n", "")
    js = must_replace(
        js,
        """    var data = {};
    new FormData(form).forEach(function (value, key) { data[key] = value; });
    return fetch('/api/quote', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data)
    }).then(function (res) { if (!res.ok) throw new Error('send failed'); });
""",
        """    var data = new FormData(form);
    data.append('action', 'sonic_quote');
    return fetch(sonicQuote.ajaxUrl, { method: 'POST', body: data, credentials: 'same-origin' })
      .then(function (res) { return res.json(); })
      .then(function (res) { if (!res || !res.success) throw new Error('send failed'); });
""",
    )
    (THEME / "assets" / "js" / "main.js").write_text(js, encoding="utf-8")

    # --- Pages
    descriptions = {}
    footer = None
    for source, (slug, title) in PAGES.items():
        html = (SITE / source).read_text(encoding="utf-8")
        desc = between(html, '<meta name="description" content="', '">')

        if source == "dashboard.html":
            descriptions[slug] = desc
            (THEME / "assets" / "css" / "dashboard.css").write_text(between(html, "<style>\n", "</style>"), encoding="utf-8")
            (THEME / "assets" / "js" / "dashboard.js").write_text(
                between(html, "<script>\n", "</script>", last=True), encoding="utf-8"
            )
            body = between(html, "<body>\n", "<script>").strip()
            (THEME / f"page-{slug}.php").write_text(DASHBOARD_PHP.replace("__BODY__", wp_links(body)), encoding="utf-8")
            continue

        body = between(html, "<body>\n", '<footer class="footer">')
        if footer is None:
            footer = '<footer class="footer">' + between(html, '<footer class="footer">', "</footer>") + "</footer>"

        template = (
            PAGE_PHP.replace("__TITLE__", title)
            .replace("__SOURCE__", source)
            .replace("__BODY__", wp_links(body).strip() + "\n")
        )
        if slug is None:
            home_desc = desc
            (THEME / "front-page.php").write_text(template, encoding="utf-8")
        else:
            descriptions[slug] = desc
            (THEME / f"page-{slug}.php").write_text(template, encoding="utf-8")

    footer = wp_links(footer)
    footer = must_replace(footer, '<span id="year">2026</span>', "<span id=\"year\"><?php echo esc_html( gmdate( 'Y' ) ); ?></span>")
    (THEME / "footer.php").write_text(FOOTER_PHP.replace("__FOOTER__", footer), encoding="utf-8")

    # --- Shared files
    pages_php = "\n".join(
        "\t\t'%s' => '%s'," % (slug, php_str(title)) for slug, title in PAGES.values() if slug
    )
    desc_php = "\n".join("\t\t'%s' => '%s'," % (slug, php_str(text)) for slug, text in descriptions.items())
    functions = (
        FUNCTIONS_PHP.replace("__VERSION__", VERSION)
        .replace("__FONTS_URL__", FONTS_URL)
        .replace("__PAGES__", pages_php)
        .replace("__DESCRIPTIONS__", desc_php)
        .replace("__HOME_DESCRIPTION__", php_str(home_desc))
    )
    (THEME / "functions.php").write_text(functions, encoding="utf-8")
    (THEME / "header.php").write_text(HEADER_PHP, encoding="utf-8")
    (THEME / "index.php").write_text(INDEX_PHP, encoding="utf-8")
    (THEME / "readme.txt").write_text(README_TXT, encoding="utf-8")

    # Theme thumbnail for the WordPress admin (macOS only; skipped elsewhere).
    shot = THEME / "screenshot.png"
    try:
        subprocess.run(
            ["sips", "-s", "format", "png", "--resampleHeight", "900", "-c", "900", "1200",
             str(SITE / "assets" / "img" / "hero-warehouse.jpg"), "--out", str(shot)],
            check=True, capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError):
        print("Skipped screenshot.png (sips not available)")

    # --- Zip
    zip_path = OUT / "sonic-fulfillment.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for f in sorted(THEME.rglob("*")):
            if f.is_file() and f.name != ".DS_Store":
                z.write(f, f.relative_to(OUT))

    print(f"Theme folder: {THEME}")
    print(f"Upload file:  {zip_path} ({zip_path.stat().st_size / 1e6:.1f} MB)")


if __name__ == "__main__":
    build()
